services:
  lessonplansys:
    image: lessonplansys
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - "8080:8080"
    environment:
      DB_URL: trng2044-rds-1.chueiwozbnfz.us-east-1.rds.amazonaws.com:5432/Group2
    secrets:
      - db_password
      - db_username

secrets:
  db_password:
    file: ./secrets/db_password.txt
  db_username:
    file: ./secrets/db_username.txt
